name: Build MacOS

on: [push, pull_request]

jobs:
  Build:
    strategy:
      matrix:
        qt_version: [6.1.2, 6.6.0]
        platform: [macos-latest]
        arch: [x64]
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Installing Qt
        uses: jurplel/install-qt-action@v4.0.0
        with:
          version: ${{ matrix.qt_version }}
          arch: ${{ matrix.qtarch }}
          cached: 'false'

      - name: Build
        shell: bash
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build . --parallel $(nproc)
