name: Build

on: [push, pull_request]

jobs:
  Build:
    strategy:
      matrix:
        qt_version: [5.15.1]
        platform: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, ubuntu-latest]
        arch: [x64]
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Installing Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.qt_version }}
          arch: ${{ matrix.qtarch }}
          cached: 'false'

      - name: Build
        shell: bash
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .