name: CMake

on: [push, pull_request]

jobs:
  cmake-format:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Install cmake-format
        run: pip install cmake-format

      - name: Run cmake-format
        run: |
          cmake-format -i ./CMakeLists.txt
          cmake-format -i ./src/CMakeLists.txt

      - name: Add & Commit
        uses: EndBug/add-and-commit@v9
        with:
          signoff: true
          message: 'Format cmake files'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
